services:
  postgres:
    image: postgres:15
    container_name: EA
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  #TODO for verifyEmail
  # mailhog:
  #   image: mailhog/mailhog:latest
  #   container_name: mailhogEA
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
  #   restart: unless-stopped
volumes:
  pg_data:
